version: '3.8'
services:
  mysql:
    platform: linux/x86_64
    build:
      context: .
      dockerfile: Dockerfile-database
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: test123!
      MYSQL_ROOT_PASSWORD: root123!
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
volumes:
  db-data: