services:
  mysql:
    platform: linux/x86_64
    image: mysql:8.0.26
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: test123!
      MYSQL_ROOT_PASSWORD: root123!
    ports:
      - "3306:3306"
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - db-data:/var/lib/mysql
volumes:
  db-data: